# EDCOP Kibana Chart values
image:
  # Basic image: docker.elastic.co/kibana/kibana:6.4.0
  kibana: docker.elastic.co/kibana/kibana:6.4.0
networks:
  # Overlay is the name of the default cni network
  overlay: calico
nodeSelector:
  label: infrastructure
ingress:
  #Enter the subdomain and the FQDN that will be used to access Kibana
  host: kibana.edcop.io  
